### PR TITLE
workaround/fix for loading qt libraries

### LINKED ISSUE #14: Error while loading shared libraries: libQt5Core.so.5
Latest only outputs:
```
Command used to start the mumble-server : /usr/bin/mumble-server -fg -ini /etc/murmur/murmur.ini -v
/usr/bin/mumble-server: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

Run command:
`sudo docker run -d -p 64738:64738/tcp -p 64738:64738/udp --name mumble-server-001 -e DEBUG=0 mumblevoip/mumble-server`

What am I missing here?

### PR DESCRIPTION
**Pull request by fgma**
Fixes loading of qt libraries on CentOS.

Fixes #14

### CODE REVIEW

**Review by Krzmbrzl — CHANGES_REQUESTED** [review]
There should also be a comment explaining what this does and why it is necessary

**Comment by fgma** [comment]
@Krzmbrzl I've added a comment. Let me know if something is still missing.

**Comment by azlux** [comment]
I will check if the server working on ubuntu/debian/raspberry with your change before merging.
If no, we will make a separate build.

**Comment by fgma** [comment]
I've tested it on debian amd64. Works as expected.

**Comment by azlux** [comment]
> I've tested it on debian amd64. Works as expected.

Good for me too

**Review by Krzmbrzl — APPROVED** [review]

**Pull request merged**
